import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "next-themes";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter, Schoolbell } from "next/font/google";
import Navbar from "@/components/shared/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


const schoolbell = Schoolbell(
    {
        subsets: ["latin"],
        weight: "400",
        variable: "--font-schoolbell",
    }
);

const inter = Inter({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-inter",
});

export default function CoreRootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={cn(
            "min-h-screen font-sans antialiased mx-auto",
            inter.variable,
            schoolbell.variable,
            inter.className,
        )}
        >
            {children}
            <Navbar />
        </div>
    );
}